### PR TITLE
Add enrollment dates to untap / fix sqlite import issues

### PR DESCRIPTION
**Pull request by nouyang-curoverse**

### CODE REVIEW

**Comment by abeconnelly** [comment]
When running, I get "mv: cannot move `scratch/huXXXXXX' to out-data/scratch/huXXXXXX': File exists" (where "XXXXXX" is the latter portion of each persons huID).

Running on one of my systems I've found the culprit line to be:

https://github.com/nouyang-curoverse/untap/blob/1a307444a0137ea756bbf27974a653f9eca79a97/public-database-snapshot#L80

I don't want to merge until this issue is resolved.

**Comment by nouyang-curoverse** [comment]
Huh, I don't see how that'd be the case unless you ran it more than once. Perhaps we could include a cleanup script that deletes all the data, or alternatively use rsync instead to overwrite the data existing in `out-data/scratch/` and `out-data/stage`? Let me know what you think.

**Comment by abeconnelly** [comment]
As long as there are no stale files I'm agnostic.

**Comment by nouyang-curoverse** [comment]
Fixed in a different way.

**Pull request closed without merging**
